#%RAML 1.0
title: second-raml
/customer:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "result":"sucesffuly fetch the data"
              }
    